const heistmembers = [
  {
    charname: "Professor",
    imageurl:
      "https://i.pinimg.com/originals/be/a3/69/bea369b891f803cf2716ba5338eeb7f0.jpg",
    realname: "alvaro morte",
    dob: "23 FEB 1975",
    age: 47,
    nationality: "spanish",
    sociallink: "https://www.instagram.com/alvaromorte/?hl=en",
  },
  {
    charname: "Tokyo",
    imageurl:
      "https://cutewallpaper.org/22/money-heist-tokyo-wallpapers/1793922960.jpg",
    realname: "ursula corbero",
    dob: "11 AUG 1989",
    age: 32,
    nationality: "spanish",
    sociallink: "https://www.instagram.com/ursulolita/?hl=en",
  },
  {
    charname: "berlin",
    imageurl:
      "https://files.oyebesmartest.com/uploads/preview/aesthetic-berlin-money-hev5lyi.webp",
    realname: "perdo alonso",
    dob: "21 JUN 1971",
    age: 51,
    nationality: "spanish",
    sociallink: "https://www.instagram.com/pedroalonsoochoro/?hl=en",
  },
  {
    charname: "rio",
    imageurl: "https://wallpapercave.com/wp/wp5954398.jpg",
    realname: "Miguel Herrán",
    dob: "25 APRIL 1996",
    age: 26,
    nationality: "spanish",
    sociallink: "https://www.instagram.com/miguel.g.herran/?hl=en",
  },
  {
    charname: "raquel",
    imageurl: "https://wallpaperaccess.com/full/2866821.jpg",
    realname: "Itziar Ituño",
    dob: "18 JUN 1974",
    age: 48,
    nationality: "spanish",
    sociallink: "https://www.instagram.com/itziarituno/?hl=en",
  },
  {
    charname: "denver",
    imageurl:
      "https://fsb.zobj.net/crop.php?r=YkNfrl2_GuND7Hy2z7djKC0fdENm4JZqdrF_ggOZctRkK1NBzu0HsifdfftrnPPzAHDHa287uZlrMO0XseGKYB6TYQcO0KgVFVt9alQIp8MmoVkiDrA65UrOPxq2lfKjdQn1h32NoV7GO69Hdjc0OWAA8YMwyaUPJFVip1sJJubJI7s6O2t7lexMp1IgnOZ4suKW8AXwMWbafdih",
    realname: "Jaime Lorente",
    dob: "12 DEC 1991",
    age: 30,
    nationality: "spanish",
    sociallink: "https://www.instagram.com/jaimelorentelo",
  },
  {
    charname: "nairobi",
    imageurl:
      "https://wallpapers.com/images/high/nairobi-money-heist-pictorial-spava5cz7awak97v.jpg",
    realname: "alba flores",
    dob: "27 OCT 1986",
    age: 35,
    nationality: "spanish",
    sociallink: "https://www.instagram.com/albafloresoficial",
  },
  {
    charname: "monica gaztambede",
    imageurl: "https://wallpapercave.com/wp/wp6577923.jpg",
    realname: "esther acebo",
    dob: "19 JAN 1983",
    age: 39,
    nationality: "spanish",
    sociallink: "https://www.instagram.com/estheracebo",
  },
  {
    charname: "helsinki",
    imageurl: "https://wallpaperaccess.com/full/2649734.jpg",
    realname: "Darko Perić",
    dob: "25 MAR 1977",
    age: 45,
    nationality: "serbian",
    sociallink: "https://www.instagram.com/darkoperich/",
  },
  {
    charname: "sierra",
    imageurl:
      "https://image.tmdb.org/t/p/original/lH7WlPDNy743YNq9XsdLygClBCD.jpg",
    realname: "Najwa Nimri",
    dob: "14 FEB 1972",
    age: 50,
    nationality: "spanish",
    sociallink: "https://www.instagram.com/najwanimri",
  },
  {
    charname: "palermo",
    imageurl:
      "https://1847884116.rsc.cdn77.org/ampigstory/1632400396882/file-1632400396909.jpg",
    realname: "Rodrigo de la Serna",
    dob: "18 APR 1976",
    age: 46,
    nationality: "argentine",
    sociallink: "https://www.instagram.com/delaserna_rodrigo/",
  },
  {
    charname: "moscow",
    imageurl:
      "https://i.pinimg.com/originals/d1/64/bb/d164bb835472d9d687f09ae6b04732fe.jpg",
    realname: "paco tous",
    dob: "1964",
    age: 58,
    nationality: "spanish",
    sociallink: "https://www.instagram.com/pacotous/",
  },
  {
    charname: "bogota",
    imageurl:
      "https://cutewallpaper.org/22/moscow-money-heist-wallpapers/1907824482.jpg",
    realname: "Hovik Keuchkerian",
    dob: "14 NOV 1972",
    age: 49,
    nationality: "lebanese",
    sociallink: "https://www.instagram.com/hovik_keuchkerian/",
  },
  {
    charname: "marsella",
    imageurl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/2021-10-30_17-11-50_ILCE-7C_DSC09731_-_Luka_Pero%C5%A1_%28cropped%29.jpg/1200px-2021-10-30_17-11-50_ILCE-7C_DSC09731_-_Luka_Pero%C5%A1_%28cropped%29.jpg",
    realname: "Luka Peroš",
    dob: "28 OCT 1976",
    age: 45,
    nationality: "croatia",
    sociallink: "https://www.instagram.com/lukaperosofficial/",
  },
  {
    charname: "oslo",
    imageurl: "https://wallpapercave.com/wp/wp9057121.jpg",
    realname: "Roberto García Ruiz",
    dob: "5 MAR 1974",
    age: 48,
    nationality: "spanish",
    sociallink: "https://wallpapercave.com/wp/wp9057121.jpg",
  },
];
export default heistmembers;
